// Seed data for the Cookbook app.
// Loaded into IndexedDB on first run only (when the database is empty).
// After that, the "Add dish" form is the source of new dishes.
//
// Shape matches the data model in the brief:
//   id, name, origin[], timeCategory, mealType[], ingredients[], appliances[], steps[], photos[], timers[]
// - origin: array of tags. A dish can have multiple (e.g. ["Chinese", "Taiwanese"]).
// - mealType: array of tags from ["Snack", "Breakfast", "Proper meal"]. A dish can have multiple.
// - photos: empty here; added later via the app (upload).
// - timers: array of { label, seconds }. Empty array = no timer.

export const seedDishes = [
  {
    id: "cast-iron-steak",
    name: "Cast Iron Steak",
    origin: ["American"],
    timeCategory: "medium",
    mealType: ["Proper meal"],
    ingredients: [
      "1 steak (ribeye or sirloin)",
      "Salt",
      "Black pepper",
      "Canola oil",
      "Butter",
      "2 cloves garlic (optional)",
      "A few sprigs thyme (optional)",
    ],
    appliances: ["Cast iron pan", "Tongs"],
    steps: [
      "Take the steak out ~30 min early to come to room temperature. Pat completely dry.",
      "Season generously with salt and pepper on both sides.",
      "Heat the cast iron pan over high until just smoking. Add oil.",
      "Lay the steak away from you. Sear undisturbed ~2.5 min until a deep crust forms.",
      "Flip. Add butter, garlic, and thyme. Sear the second side ~1.5 min, spooning the foaming butter over the top.",
      "Pull at your target doneness (use a thermometer if unsure). Rest on a board ~5\u201310 min before slicing.",
    ],
    photos: [],
    timers: [
      { label: "First sear", seconds: 150 },
      { label: "Second sear", seconds: 90 },
    ],
  },
  {
    id: "century-egg-tofu",
    name: "Century Egg and Tofu \uFF08\u76AE\u86CB\u8C46\u8150\uFF09",
    origin: ["Chinese", "Taiwanese"],
    timeCategory: "fast",
    mealType: ["Proper meal"],
    ingredients: [
      "1 block silken tofu",
      "1 century egg",
      "1 tbsp soy sauce",
      "1 tsp sesame oil",
      "1 scallion (chopped)",
      "Bonito flakes (optional)",
      "Pinch of sugar (optional)",
    ],
    appliances: ["Knife"],
    steps: [
      "Gently turn the tofu out onto a plate. Slice or cube it.",
      "Peel the century egg and cut into wedges. Arrange over the tofu.",
      "Mix soy sauce and sesame oil; drizzle over.",
      "Top with chopped scallion. Serve cold.",
    ],
    photos: [],
    timers: [],
  },
  {
    id: "scrambled-eggs",
    name: "Scrambled Eggs",
    origin: ["American"],
    timeCategory: "fast",
    mealType: ["Breakfast"],
    ingredients: [
      "2 eggs",
      "Butter",
      "Salt",
      "Black pepper",
    ],
    appliances: ["Non-stick pan", "Spatula", "Bowl", "Whisk/fork"],
    steps: [
      "Crack eggs into a bowl, add a pinch of salt. Whisk well.",
      "Melt butter in a non-stick pan over low-medium heat.",
      "Pour in eggs. Let sit a few seconds, then gently push from the edges to the center with a spatula.",
      "Keep folding gently and pulling it on and off the heat \u2014 they finish cooking from residual heat.",
      "Season with pepper and serve immediately.",
    ],
    photos: [],
    timers: [],
  },
  {
    id: "carbonara",
    name: "Carbonara",
    origin: ["Italian"],
    timeCategory: "time-consuming",
    mealType: ["Proper meal"],
    ingredients: [
      "Spaghetti",
      "100g guanciale or pancetta or fatty ham",
      "3 egg yolks",
      "50g pecorino romano (grated)",
      "Black pepper",
      "Salt",
    ],
    appliances: ["Pot", "Pan", "Bowl", "Tongs", "Grater"],
    steps: [
      "Boil a pot of well-salted water. Add spaghetti and cook to al dente (~7 min).",
      "Meanwhile, cut guanciale or ham into strips and render in a dry pan over medium until crisp. Turn off heat.",
      "In a bowl, whisk egg yolks and grated pecorino into a paste.",
      "Reserve a cup of pasta water. Drain pasta and add it to the pan with the guanciale (off heat).",
      "Add a splash of pasta water, then pour in the egg mixture, tossing fast and constantly so it forms a creamy sauce without scrambling. Loosen with more pasta water as needed.",
      "Serve immediately with extra pecorino and pepper.",
    ],
    photos: [],
    timers: [
      { label: "Pasta boil", seconds: 420 },
    ],
  },
  {
    id: "scallion-beef",
    name: "Scallion Beef \uFF08\u8525\u7206\u725B\u8089\uFF09",
    origin: ["Chinese", "Taiwanese"],
    timeCategory: "medium",
    mealType: ["Proper meal"],
    ingredients: [
      "300g sliced beef",
      "Scallions",
      "3 cloves garlic (sliced)",
      "Chilis",
      "2 tbsp soy sauce",
      "1 tsp sugar",
      "Vegetable oil",
    ],
    appliances: ["Wok or large pan", "Spatula", "Bowl"],
    steps: [
      "Marinate sliced beef with 1 tbsp soy sauce for ~15 min.",
      "Heat wok until very hot, add oil. Sear beef in a single layer until just browned, then remove (it shouldn't be fully cooked through).",
      "Add a little more oil, fry garlic and chilis briefly until fragrant.",
      "Add 2\" pieces of scallion whites first, stir a few seconds, then return the beef. Toss over high heat.",
      "Add scallion greens last, toss until just wilted. Serve hot with rice.",
    ],
    photos: [],
    timers: [],
  },
  {
    id: "oyakodon",
    name: "Oyakodon",
    origin: ["Japanese"],
    timeCategory: "medium",
    mealType: ["Proper meal"],
    ingredients: [
      "1 chicken thigh (bite-sized pieces)",
      "2 eggs (lightly beaten)",
      "\u00BD onion (sliced)",
      "1 scallion (chopped)",
      "1 serving cooked rice",
      "Dashi (\u00BD cup)",
      "1.5 tbsp soy sauce",
      "1 tbsp mirin",
      "1 tsp sugar",
    ],
    appliances: ["Pan", "Rice cooker", "Bowl"],
    steps: [
      "In a small pan, combine dashi, soy sauce, mirin, and sugar. Bring to a gentle simmer.",
      "Add sliced onion and simmer until softened.",
      "Add chicken pieces and simmer until cooked through.",
      "Pour the beaten egg over evenly. Cover and cook on low until the egg is just set but still soft (don't overcook).",
      "Slide over a bowl of hot rice. Top with chopped scallion.",
    ],
    photos: [],
    timers: [],
  },
  {
    id: "soba",
    name: "Chilled / Hot Soba",
    origin: ["Japanese"],
    timeCategory: "medium",
    mealType: ["Proper meal"],
    ingredients: [
      "1 bundle soba noodles",
      "Soba tsuyu (store-bought dipping/soup base)",
      "Kombu",
      "Soy sauce",
      "Mirin",
      "1 scallion (chopped)",
      "Nori strips",
      "Bonito flakes",
      "Wasabi (optional)",
    ],
    appliances: ["Small pot", "Big pot", "Colander", "Bowl"],
    steps: [
      "Make dashi: put kombu and bonito flakes in cold water in the small pot, heat it on low to medium heat, slowly cook them so as not to make the dashi bitter.",
      "Make soba sauce: when the dashi starts to simmer, take out the kombu and bonito flakes, and put in mirin first, let it cook for 2 minutes, then put in soy sauce. Dashi to soy sauce to mirin = 8:1:1.",
      "Boil soba in water per package (~4\u20135 min), don't add salt, stir so they don't clump.",
      "Rinse soba under cold running water, rubbing gently to remove starch; drain well.",
      "Chilled: serve noodles on a plate/zaru with a cup of cold tsuyu for dipping. Hot: serve in a bowl with hot tsuyu poured over.",
      "Top with scallion, nori, and wasabi to taste.",
    ],
    photos: [],
    timers: [
      { label: "Noodle boil", seconds: 270 },
    ],
  },
  {
    id: "pancakes",
    name: "Pancakes",
    origin: ["American"],
    timeCategory: "medium",
    mealType: ["Snack", "Breakfast"],
    ingredients: [
      "Whole milk (386g)",
      "All-purpose flour (300g)",
      "1 egg",
      "Salt (4g)",
      "Baking soda (1g)",
      "Butter (21g)",
      "Sugar (62g)",
    ],
    appliances: ["Pan", "Bowl", "Whisk", "Ladle", "Spatula"],
    steps: [
      "Whisk together flour, sugar, baking soda, and salt in a bowl.",
      "In another bowl, whisk milk, egg, and melted butter.",
      "Pour wet into dry and mix until combined.",
      "Heat a lightly buttered non-stick pan over medium. Ladle in batter.",
      "Cook until bubbles form on top and edges look set, then flip and cook until golden.",
      "Repeat with the rest. Serve with butter and syrup.",
    ],
    photos: [],
    timers: [],
  },
  {
    id: "air-fried-potato-chips",
    name: "Air-Fried Potato Chips",
    origin: ["American"],
    timeCategory: "medium",
    mealType: ["Snack"],
    ingredients: [
      "2 potatoes (thinly sliced)",
      "1 tbsp oil",
      "Salt",
      "Pepper (optional)",
    ],
    appliances: ["Air fryer", "Mandoline", "Knife", "Bowl"],
    steps: [
      "Slice potatoes very thinly (a mandoline helps). Soak slices in cold water ~15 min to remove starch, then pat completely dry.",
      "Toss with oil and a little salt.",
      "Arrange in a single layer in the air fryer basket (work in batches if needed).",
      "Air fry at ~350\u00B0F, tossing/shaking halfway, until golden and crisp (~15 min total \u2014 watch closely near the end, they burn fast).",
      "Season with salt and pepper while hot.",
    ],
    photos: [],
    timers: [
      { label: "Air fry", seconds: 900 },
    ],
  },
];
